name: pygsaw2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.1.1
  - pytest
  - tqdm
  - pillow=7.2
  - aggdraw=1.3.11
  - pip:
    - vecrec
#    - pyglet==1.5.5
#    - glooey==0.3.0
    - pyqtree==1.0.0